### ISSUE TITLE
Recursive Upsert or CreateOrGet

### ISSUE THREAD

**Issue by protheusfr** [dolan-in/dgman#37]
Hello,

Is there a way to recursively CreateOrGet node via dgman ?

As exemple, let say we have the following structure / schema :

```
type T1 struct {
	UID  string `json:"uid,omitempty"`
	Name string `json:"name,omitempty"  dgraph:"index=exact unique"`
	T2s  []T2   `json:"t2s,omitempty"`
        DType            []string   `json:"dgraph.type,omitempty"`
}

type T2 struct {
	UID string `json:"uid,omitempty"`
	Age int    `json:"age,omitempty"  dgraph:"index=exact unique"`
	T3s []T3   `json:"t3s,omitempty"`
        DType            []string   `json:"dgraph.type,omitempty"`
}

type T3 struct {
	UID   string `json:"uid,omitempty"`
	Color string `json:"color,omitempty"  dgraph:"index=exact unique"`
        DType            []string   `json:"dgraph.type,omitempty"`
}
```

Then we want mutate the two following instances : 

```
	test1 := T1{
		Name: "testName",
		T2s: []T2{
			{
				Age: 30,
				T3s: []T3{
					{
						Color: "blue",
					},
					{
						Color: "Red",
					},
				},
			},
		},
	}

	test2 := T1{
		Name: "testName",
		T2s: []T2{
			{
				Age: 30,
				T3s: []T3{
					{
						Color: "yellow",
					},
					{
						Color: "Red",
					},
				},
			},
		},
	}
```

With the following result in the graph : 

```
{
  "data": {
    "T1": [
      {
        "name":"testName",
        "t2s": [
          {
            "age": "30",
            "t3s": [
              {
                "color": "blue",
              },
              {
                "color": "Red",
              },
              {
                "color": "yellow",
              }
             ]
       }
      ]
  }
```

Then, an equivalent to `MERGE` instruction in Cypher  based on `unique` tag for node existence detection ?

**Comment by wildan2711** [comment]
Again, this is similar to your previous issue, as dgman currently only checks the first depth of the node structure. This is significantly more difficult.

So you want to maintain uniqueness on the `name` and `age` field? I don't have any knowledge of Cypher, but is this possible in Cypher on a single mutation? Can you give an example.

**Comment by protheusfr** [comment]
That's correct, and agree, this is significant more difficult.
You can get MERGE exemples with Cypher on this page : https://neo4j.com/docs/cypher-manual/current/clauses/merge/#merge-merge-on-multiple-relationships

The main issue for me is the absence of uniques constraint on dGraph predicates.

**Comment by wildan2711** [comment]
> The main issue for me is the absence of uniques constraint on dGraph predicates.

Yes, this is one of the main reasons I created this library. 

I have a rough idea how I will implement recursive unique checking, though this will take significantly more time.

**Comment by wildan2711** [comment]
Btw, you can try using the new [@noconflict](https://docs.dgraph.io/query-language/#noconflict-directive) directive in Dgraph and see if it fits your needs.

Currently, it enforces uniqueness on the predicate level, but I don't think it supports on the type level.

**Comment by protheusfr** [comment]
Interesting, thank you.
it seems dGraph 2.0.0 will also include an uniques directive via GraphQL type definition (see : https://graphql.dgraph.io/)...

**Comment by wildan2711** [comment]
Yeah, just realized there was a `@id` directive, still can't find the GraphQL+- equivalent.

**Comment by protheusfr** [comment]
Yes I think this not just a langage add but linked to a deep evolution of how dGraph 2 manage transactions.

**Comment by wildan2711** [comment]
After a bit of research, the `@id` just creates an `upsert` directive, which only check uniqueness through the `/graphql` endpoint. If you manually add nodes using GraphQL+- mutations, it won't check for uniqueness.

**Comment by wildan2711** [comment]
Yes, after a bit of research, the `@id` just adds an `upsert` directive on the predicate, if you insert a node manually using GraphQL+- mutations or from the grpc client, there is no unique checking. 

Currently, we would have to rely doing mutations from the GraphQL endpoint to utilize unique checking with the `@id` directive. 

Not much we can use here currently.

**Comment by wildan2711** [comment]
Hi @protheusfr,

To add recursive unique checking required a major rewrite on the mutation helpers. So this is included as a major version bump to v2, which includes many breaking changes. `CreateOrGet` is renamed to `MutateOrGet`, while `Upsert` remains.

If you're interested you can try it out on the [v2.0.0-alpha.1](https://github.com/dolan-in/dgman/releases/tag/v2.0.0-alpha.1) version.
