### ISSUE TITLE
Recursive UID injection on mutate

### ISSUE THREAD

**Issue by freb** [dolan-in/dgman#46]
This is related to #35, recursive type injection on mutate. Since that issue was fixed, it is now possible to perform a mutate on nested structs. However, the UID will only be updated on the root node/struct, not on the created children.

I'm not sure how much this will affect me, but wanted to raise an issue to document it.

**Comment by wildan2711** [comment]
Hi @freb, this is fixed in the `v2` version, which you can try it out on the [v2.0.0-alpha.1](https://github.com/dolan-in/dgman/releases/tag/v2.0.0-alpha.1) pre-release.

Thanks for the idea in using `reflectwalk`!
