### ISSUE TITLE
Error on mutate for interface slice

### ISSUE THREAD

**Issue by freb** [dolan-in/dgman#58]
When loading test data, I need to be able to mutate all data in the same query, otherwise handling referencing between nodes submitted in different queries becomes difficult. My current solution is to hard code Uids, which I'd like to avoid is some cases.

What I really want to be able to do is run mutate with a `[]interface{}` type, where the elements are pointers to any of my model structs. I found #3 and thought that this should be supported, but I kept getting errors. I think with a simple change this should work as I expected, changing [these lines](https://github.com/dolan-in/dgman/blob/master/mutate.go#L527-L529) to:

```go
if elVal.Kind() == reflect.Interface {
	elVal = elVal.Elem()
}
if elVal.Kind() == reflect.Ptr {
	elVal = elVal.Elem()
}
```

You basically just need another unwrap of the reflect Value to account for interface. When passing a slice to `injectType`, it also doesn't seem like it should be necessary to pass a pointer  to a slice. I have only testing this using `injectType` directly, so I don't know if the `mutate` function has other checks that would fail when handling a `[]interface{}` for data.

On a related note, would you have any interest in exporting `injectType` so that it could be used directly?

**Comment by wildan2711** [comment]
Current implementation for the mutation helpers only account for a single type of slice, not a `[]interface{}`. 

Do you need this only for injecting types? Or the mutation helpers, i.e: unique checking? If the former, yes, I think the above fix would suffice, if the latter, it would quite need a revamp on how we resolve types.

> On a related note, would you have any interest in exporting injectType so that it could be used directly?

Yes, if it is useful, then it should to be exported.

**Comment by freb** [comment]
> Current implementation for the mutation helpers only account for a single type of slice, not a `[]interface{}`.

Ahh, I think I must have had two issues then: (1) not passing a pointer to a slice and (2) using an interface type. I don't think I ever tried, for example `*[]*User`.

After opening this issues I found <github.com/mitchellh/reflectwalk> which helped me duplicate injectType in a way that I'm happy with. Since the current behavior is as expected, I'll go ahead and close this. Sorry for the noise.

One last note. Using that same library I also implemented functions for setting blank uids and filling the blank values in with the uid map from the mutate response. All the functions recurse whichever types you want to provide. I'm not sure if you'd find it interesting or helpful, but I'd be happy to paste them here if you'd like to take a look.

**Comment by wildan2711** [comment]
Cool, that would be great to paste them here. I'm looking at different
solutions to apply recursive injection of the created uid's.

**Comment by freb** [comment]
I created a gist: https://gist.github.com/freb/6846fd71a2ddff14ac4d80e5588b977d

Let me know what you think. You'll see three functions:

```
SetTypes
SetUids
GenUids
```

**Comment by wildan2711** [comment]
Cool.. I'll look into it.

**Comment by wildan2711** [comment]
Hi, @freb thansk for the gist! I also recently found problems setting types on interface slice, your solution fixed it, and the code was also cleaner thanks to it.

#61
